services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app  
      - ./ollama_models:/root/.ollama/models
      - ./start.sh:/start.sh
      - ./app/requirements.txt:/app/requirements.txt
      - data_volume:/app/data
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    container_name: postgres_db
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pebkac
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pgvector/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql

  angular:
    build:
      dockerfile: Dockerfile.angular
    ports: 
      - "4200:4200"

  data_processing:
    build:
      context: .
      dockerfile: Dockerfile.data_processing
    volumes:
      - data_volume:/app/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  data_volume: