services:
  test_runner:
    container_name: mvp_test_runner
    image: python:3.12
    volumes:
      - .:/test
    working_dir: /test
    command: >
      sh -c "pip install -r app/requirements.txt && python -m unittest discover -s tests -p '*_test.py'"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    container_name: postgres_db
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pebkac
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pgvector/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql

volumes:
  postgres_data: