# copiato da Matteo e Derek
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app  
      - ./ollama_models:/root/.ollama/models
      - ./start.sh:/start.sh
      - ./app/requirements.txt:/app/requirements.txt
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    container_name: postgres_db
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pebkac
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pgvector/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql

volumes:
  postgres_data: